sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    #需要填写自己的数据库用户名和密码
    username: root
    password: root

  #自己填写阿里云信息
  alioss:
        endpoint: oss-cn-beijing.aliyuncs.com
        access-key-id: LTAI5tAbcd1234
        access-key-secret: Xyz7890abcde
        bucket-name: my-sky-takeout
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid:  wx79ca4356f295ce9e
    secret: 3872a270123ce79a86c1f98d3c0f704c
    #ID和密钥需要自己申请小程序后获取
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
